### ISSUE TITLE
我正在尝试构建早期版本卡池（大约903）的ygomobile，我应如何获得早期版本的人机

### ISSUE THREAD

**Issue by SuperLemonJerry** [mercury233/libWindbot#2]
你好，我目前正在构建一个903版本的卡池，如果我想用早期旧版本的AI，我应该从什么地方获取

**Comment by mercury233** [comment]
使用当前版本的pro但从数据库去掉新卡就好了，在人机列表里也去掉使用了新卡的人机，或者通过禁卡表把新卡变成人机专属

**Comment by SuperLemonJerry** [comment]
黑羽人机已经从目前版本移除，但是我看编译里面还有黑羽人机，我应该怎么样把黑羽人机恢复到配置里面可以选中决斗

**Comment by mercury233** [comment]
黑羽是未完成，但和其他人机一样在bot.conf加入就可以用

**Comment by SuperLemonJerry** [comment]
!谜之剑士LV4-异热同心武器
Name=谜之剑士LV4 Deck='Zexal Weapons' Dialog=swordsman.zh-CN
神装电光皇卡组。
AI_LV2 SUPPORT_MASTER_RULE_3

bot.conf 是类似于这样的配置，但是他的对应卡组是[AI_ZexalWeapons.ydk] 在上面的配置没有出现过。如果我需要追加黑羽卡组人机,是不是需要修改其他地方的配置。

**Comment by mercury233** [comment]
windbot的readme里有列表

**Comment by SuperLemonJerry** [comment]
windbot的readme里只有列表，但并没有 卡组 和 对应的ydk文件的映射关系。
!谜之剑士LV4-异热同心武器
Name=谜之剑士LV4 Deck='Zexal Weapons' Dialog=swordsman.zh-CN
神装电光皇卡组。
AI_LV2 SUPPORT_MASTER_RULE_3
就像上面这一配置，我应该如何改动。

**Comment by mercury233** [comment]
对应关系在windbot的源码的executor的属性里，你需要改的是卡组的名字
```
!谜之剑士LV4-黑羽
Name=谜之剑士LV4 Deck=Blackwing Dialog=swordsman.zh-CN
不太会玩的黑羽卡组。
AI_LV2 SUPPORT_MASTER_RULE_3
```
